name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    uses: ./.github/workflows/preliminaries.yml
    with:
      task: go test -v ./...

  lint:
    uses: ./.github/workflows/preliminaries.yml
    with:
      task: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
          | sh -s -- -b $(go env GOPATH)/bin v1.61.0
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        golangci-lint run ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Cache Go modules and build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.txt ./...
          go tool cover -func=coverage.txt

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.txt

  upload-coverage:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - uses: actions/checkout@v4

      - name: Download coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.txt
